<?php
namespace App\Constraint;

use Symfony\Component\Validator\Constraint;
class AuthConstraint extends Constraint
{
    public $message = 'The string "{{ string }}" contains an illegal character: it can only contain letters or numbers.';

    public function validatedBy(): string
    {
        return static::class.'Validator'; // TODO: Change the autogenerated stub
    }
}
