version: '3.8'
networks:
  sql_php:
    driver: bridge
services:
  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: RK@Y14S19R5u
    ports:
      - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql
  php:
    container_name: php-container
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - db
    networks:
      - sql_php
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - sql_php
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: RK@Y14S19R5u
    ports:
      - '8090:80'
    depends_on:
      - db
volumes:
  db_data:
